
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-26T11:43:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "67adb47b63e1c0b41d916ad3c13ad146ea8347c3",
 "version": "0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
