# Generated by Django 5.0.9 on 2024-10-15 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('risks', '0002_alter_risk_custom_field_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassignment',
            old_name='content_type',
            new_name='object_type',
        ),
        migrations.AlterUniqueTogether(
            name='riskassignment',
            unique_together={('object_type', 'object_id', 'risk', 'relation')},
        ),
    ]
