# Generated by Django 5.0.8 on 2024-08-28 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("django_celery_beat", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="RruleSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rrule", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="RrulePeriodicTask",
            fields=[
                (
                    "periodictask_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "rrule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Rrule Schedule to run the task on.  Set only one schedule type, leave the others null.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat_rrule.rruleschedule",
                        verbose_name="Rrule Schedule",
                    ),
                ),
            ],
            bases=("django_celery_beat.periodictask",),
        ),
    ]
