# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry_protos/snuba/v1/endpoint_time_series.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from sentry_protos.snuba.v1 import request_common_pb2 as sentry__protos_dot_snuba_dot_v1_dot_request__common__pb2
from sentry_protos.snuba.v1 import trace_item_attribute_pb2 as sentry__protos_dot_snuba_dot_v1_dot_trace__item__attribute__pb2
from sentry_protos.snuba.v1 import trace_item_filter_pb2 as sentry__protos_dot_snuba_dot_v1_dot_trace__item__filter__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1sentry_protos/snuba/v1/endpoint_time_series.proto\x12\x16sentry_protos.snuba.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a+sentry_protos/snuba/v1/request_common.proto\x1a\x31sentry_protos/snuba/v1/trace_item_attribute.proto\x1a.sentry_protos/snuba/v1/trace_item_filter.proto\"\x95\x02\n\x11TimeSeriesRequest\x12\x31\n\x04meta\x18\x01 \x01(\x0b\x32#.sentry_protos.snuba.v1.RequestMeta\x12\x37\n\x06\x66ilter\x18\x02 \x01(\x0b\x32\'.sentry_protos.snuba.v1.TraceItemFilter\x12\x42\n\x0c\x61ggregations\x18\x03 \x03(\x0b\x32,.sentry_protos.snuba.v1.AttributeAggregation\x12\x18\n\x10granularity_secs\x18\x04 \x01(\x04\x12\x36\n\x08group_by\x18\x05 \x03(\x0b\x32$.sentry_protos.snuba.v1.AttributeKey\"\x9d\x01\n\tDataPoint\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x02\x12\x14\n\x0c\x64\x61ta_present\x18\x02 \x01(\x08\x12\x19\n\x11\x61vg_sampling_rate\x18\x03 \x01(\x02\x12\x17\n\x0bis_reliable\x18\x04 \x01(\x08\x42\x02\x18\x01\x12\x38\n\x0breliability\x18\x05 \x01(\x0e\x32#.sentry_protos.snuba.v1.Reliability\"\xc5\x02\n\nTimeSeries\x12\r\n\x05label\x18\x01 \x01(\t\x12V\n\x13group_by_attributes\x18\x02 \x03(\x0b\x32\x39.sentry_protos.snuba.v1.TimeSeries.GroupByAttributesEntry\x12+\n\x07\x62uckets\x18\x03 \x03(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x36\n\x0b\x64\x61ta_points\x18\x04 \x03(\x0b\x32!.sentry_protos.snuba.v1.DataPoint\x12\x12\n\nnum_events\x18\x05 \x01(\x04\x12\x1d\n\x11\x61vg_sampling_rate\x18\x06 \x01(\x02\x42\x02\x18\x01\x1a\x38\n\x16GroupByAttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x87\x01\n\x12TimeSeriesResponse\x12=\n\x11result_timeseries\x18\x01 \x03(\x0b\x32\".sentry_protos.snuba.v1.TimeSeries\x12\x32\n\x04meta\x18\x05 \x01(\x0b\x32$.sentry_protos.snuba.v1.ResponseMetab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentry_protos.snuba.v1.endpoint_time_series_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATAPOINT'].fields_by_name['is_reliable']._loaded_options = None
  _globals['_DATAPOINT'].fields_by_name['is_reliable']._serialized_options = b'\030\001'
  _globals['_TIMESERIES_GROUPBYATTRIBUTESENTRY']._loaded_options = None
  _globals['_TIMESERIES_GROUPBYATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_TIMESERIES'].fields_by_name['avg_sampling_rate']._loaded_options = None
  _globals['_TIMESERIES'].fields_by_name['avg_sampling_rate']._serialized_options = b'\030\001'
  _globals['_TIMESERIESREQUEST']._serialized_start=255
  _globals['_TIMESERIESREQUEST']._serialized_end=532
  _globals['_DATAPOINT']._serialized_start=535
  _globals['_DATAPOINT']._serialized_end=692
  _globals['_TIMESERIES']._serialized_start=695
  _globals['_TIMESERIES']._serialized_end=1020
  _globals['_TIMESERIES_GROUPBYATTRIBUTESENTRY']._serialized_start=964
  _globals['_TIMESERIES_GROUPBYATTRIBUTESENTRY']._serialized_end=1020
  _globals['_TIMESERIESRESPONSE']._serialized_start=1023
  _globals['_TIMESERIESRESPONSE']._serialized_end=1158
# @@protoc_insertion_point(module_scope)
