dlite_INSTALL_ROOT = '/project/python/build/temp.linux-x86_64-cpython-312/{project}/python/build/lib.manylinux2014_x86_64-3.12'
dlite_BUILD_ROOT = '/project/python/build/temp.linux-x86_64-cpython-312'

dlite_PATH = ''
dlite_LD_LIBRARY_PATH = '/project/python/build/temp.linux-x86_64-cpython-312/src;/project/python/build/temp.linux-x86_64-cpython-312/src/utils;/project/python/build/temp.linux-x86_64-cpython-312/src/pyembed'
dlite_PYTHONPATH = '/project/python/build/temp.linux-x86_64-cpython-312/bindings/python/tmp/pip-build-env-drnqvrns/site'
dlite_STORAGE_PLUGINS = '/project/python/build/temp.linux-x86_64-cpython-312/storages/json;/project/python/build/temp.linux-x86_64-cpython-312/storages/rdf;/project/python/build/temp.linux-x86_64-cpython-312/storages/python'
dlite_MAPPING_PLUGINS = ''
dlite_PYTHON_STORAGE_PLUGINS = '/project/storages/python/python-storage-plugins'
dlite_PYTHON_MAPPING_PLUGINS = '/project/bindings/python/python-mapping-plugins'
dlite_PYTHON_PROTOCOL_PLUGINS = '/project/bindings/python/python-protocol-plugins'
dlite_TEMPLATES = '/project/tools/templates'
dlite_STORAGES = '/project/examples/storages/*.json'
