nocs: list[str] = ['IOA', 'EOR', 'VNM', 'YUG', 'BOH', 'RHO', 'AFG', 'ALB', 'ALG', 'AND', 'ANG', 'ANT', 'ARG', 'ARM', 'ARU', 'ASA', 'AUS', 'AUT', 'AZE', 'BAH', 'BAN', 'BAR', 'BDI', 'BEL', 'BEN', 'BER', 'BHU', 'BIH', 'BIZ', 'BLR', 'BOL', 'BOT', 'BRA', 'BRN', 'BRU', 'BUL', 'BUR', 'CAF', 'CAM', 'CAN', 'CAY', 'CGO', 'CHA', 'CHI', 'CHN', 'CIV', 'CMR', 'COD', 'COK', 'COL', 'COM', 'CPV', 'CRC', 'CRO', 'CUB', 'CYP', 'CZE', 'DEN', 'DJI', 'DMA', 'DOM', 'ECU', 'EGY', 'ERI', 'ESA', 'ESP', 'EST', 'ETH', 'FIJ', 'FIN', 'FRA', 'FSM', 'GAB', 'GAM', 'GBR', 'GBS', 'GEO', 'GEQ', 'GER', 'GHA', 'GRE', 'GRN', 'GUA', 'GUI', 'GUM', 'GUY', 'HAI', 'HKG', 'HON', 'HUN', 'INA', 'IND', 'IRI', 'IRL', 'IRQ', 'ISL', 'ISR', 'ISV', 'ITA', 'IVB', 'JAM', 'JOR', 'JPN', 'KAZ', 'KEN', 'KGZ', 'KIR', 'KOR', 'KOS', 'KSA', 'KUW', 'LAO', 'LAT', 'LBA', 'LBN', 'LBR', 'LCA', 'LES', 'LIE', 'LTU', 'LUX', 'MAD', 'MAR', 'MAS', 'MAW', 'MDA', 'MDV', 'MEX', 'MGL', 'MHL', 'MKD', 'MLI', 'MLT', 'MNE', 'MON', 'MOZ', 'MRI', 'MTN', 'MYA', 'NAM', 'NCA', 'NED', 'NEP', 'NGR', 'NIG', 'NOR', 'NRU', 'NZL', 'OMA', 'PAK', 'PAN', 'PAR', 'PER', 'PHI', 'PLE', 'PLW', 'PNG', 'POL', 'POR', 'PRK', 'PUR', 'QAT', 'ROU', 'RSA', 'RUS', 'RWA', 'SAM', 'SEN', 'SEY', 'SGP', 'SKN', 'SLE', 'SLO', 'SMR', 'SOL', 'SOM', 'SRB', 'SRI', 'SSD', 'STP', 'SUD', 'SUI', 'SUR', 'SVK', 'SWE', 'SWZ', 'SYR', 'TAN', 'TGA', 'THA', 'TJK', 'TKM', 'TLS', 'TOG', 'TPE', 'TTO', 'TUN', 'TUR', 'TUV', 'UAE', 'UGA', 'UKR', 'URU', 'USA', 'UZB', 'VAN', 'VEN', 'VIE', 'VIN', 'YEM', 'ZAM', 'ZIM']
countries: list[str] = ['Independent Olympic Athletes', 'Refugee Olympic Team', 'South Vietnam', 'Yugoslavia', 'Bohemia', 'Rhodesia', 'Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'American Samoa', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bangladesh', 'Barbados', 'Burundi', 'Belgium', 'Benin', 'Bermuda', 'Bhutan', 'Bosnia and Herzegovina', 'Belize', 'Belarus', 'Bolivia', 'Botswana', 'Brazil', 'Bahrain', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Central African Republic', 'Cambodia', 'Canada', 'Cayman Islands', 'Republic of the Congo', 'Chad', 'Chile', 'China', 'Ivory Coast', 'Cameroon', 'Democratic Republic of the Congo', 'Cook Islands', 'Colombia', 'Comoros', 'Cape Verde', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'Eritrea', 'El Salvador', 'Spain', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Federated States of Micronesia', 'Gabon', 'The Gambia', 'Great Britain', 'Guinea-Bissau', 'Georgia', 'Equatorial Guinea', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guam', 'Guyana', 'Haiti', 'Hong Kong', 'Honduras', 'Hungary', 'Indonesia', 'India', 'Iran', 'Ireland', 'Iraq', 'Iceland', 'Israel', 'Virgin Islands', 'Italy', 'British Virgin Islands', 'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya', 'Kyrgyzstan', 'Kiribati', 'South Korea', 'Kosovo', 'Saudi Arabia', 'Kuwait', 'Laos', 'Latvia', 'Libya', 'Lebanon', 'Liberia', 'Saint Lucia', 'Lesotho', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Morocco', 'Malaysia', 'Malawi', 'Moldova', 'Maldives', 'Mexico', 'Mongolia', 'Marshall Islands', 'North Macedonia', 'Mali', 'Malta', 'Montenegro', 'Monaco', 'Mozambique', 'Mauritius', 'Mauritania', 'Myanmar', 'Namibia', 'Nicaragua', 'Netherlands', 'Nepal', 'Nigeria', 'Niger', 'Norway', 'Nauru', 'New Zealand', 'Oman', 'Pakistan', 'Panama', 'Paraguay', 'Peru', 'Philippines', 'Palestine', 'Palau', 'Papua New Guinea', 'Poland', 'Portugal', 'North Korea', 'Puerto Rico', 'Qatar', 'Romania', 'South Africa', 'Russia', 'Rwanda', 'Samoa', 'Senegal', 'Seychelles', 'Singapore', 'Saint Kitts and Nevis', 'Sierra Leone', 'Slovenia', 'San Marino', 'Solomon Islands', 'Somalia', 'Serbia', 'Sri Lanka', 'South Sudan', 'São Tomé and Príncipe', 'Sudan', 'Switzerland', 'Suriname', 'Slovakia', 'Sweden', 'Eswatini', 'Syria', 'Tanzania', 'Tonga', 'Thailand', 'Tajikistan', 'Turkmenistan', 'Timor-Leste', 'Togo', 'Chinese Taipei', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Tuvalu', 'United Arab Emirates', 'Uganda', 'Ukraine', 'Uruguay', 'United States', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Saint Vincent and the Grenadines', 'Yemen', 'Zambia', 'Zimbabwe']
noc_country_map:dict[str, str] = dict(zip(nocs, countries))
country_noc_map:dict[str, str] = dict(zip(map(lambda country: country.upper(),countries), nocs))

def noc_to_country(noc: str) -> str | None:
    return noc_country_map.get(noc.upper().strip())

def country_to_noc(country: str) -> str | None:
    return country_noc_map.get(country.upper().strip())