# Authentication
DEFAULT_AUTH_SECRET_ENV_VAR = "SSAPI_AUTH_SECRET"
DEFAULT_HOST_ENV_VAR = "SSAPI_HOST"
DEFAULT_ALLOWED_ORIGIN_ENV_VAR = "SSAPI_ALLOWED_ORIGIN"


# Database
DEFAULT_SSAPI_DATABASE_PATH = "ssapi-db.sqlite"
DEFAULT_SSAPI_TEST_DATABASE_PATH = ":memory:"

# Web
DEFAULT_SSAPI_WEB_LISTEN_PORT = 8000
DEFAULT_SSAPI_WEB_CONTENT_TYPE = "application/json"

# CORS
DEFAULT_SSAPI_ALLOW_ORIGIN = "*"
