
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-24T19:15:14-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "e3e7e628153e684f86b7ed76f4e4a1f554762857",
 "version": "0.35.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
