# Autogenerated by Astropy-affiliated package astroquery's setup.py on 2025-01-25 03:46:30 UTC
import datetime

version = "0.4.9.post1"
githash = "aea573c777e9d01c38c6d7f6b9c9786bca07856b"


major = 0
minor = 4
bugfix = 9

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2025, 1, 25, 3, 46, 30)
debug = False

astropy_helpers_version = "4.0.1"
