C
C Print simulation info
      IF (LOP .EQ. 0) THEN
      PRINT *, ' '
      PRINT *, '  ___  ___  ________     ___    ___'
      PRINT *, ' |\  \|\  \|\   __  \   |\  \  /  /|'
      PRINT *, ' \ \  \\\  \ \  \|\  \  \ \  \/  / /'
      PRINT *, '  \ \   __  \ \   __  \  \ \    / /'
      PRINT *, '   \ \  \ \  \ \  \ \  \  /     \/'
      PRINT *, '    \ \__\ \__\ \__\ \__\/  /\   \'
      PRINT *, '     \|__|\|__|\|__|\|__/__/ /\ __\'
      PRINT *, '                        |__|/ \|__|'
      PRINT *, '      01001000 01100001 01111000'
      PRINT *, '  ___  ___  ________     ___    ___ ___    ___'
      PRINT *, ' |\  \|\  \|\   __  \   |\  \  /  /|\  \  /  /|'
      PRINT *, ' \ \  \\\  \ \  \|\  \  \ \  \/  / | \  \/  / /'
      PRINT *, '  \ \   __  \ \   __  \  \ \    / / \ \    / /'
      PRINT *, '   \ \  \ \  \ \  \ \  \  /     \/   /     \/'
      PRINT *, '    \ \__\ \__\ \__\ \__\/  /\   \  /  /\   \'
      PRINT *, '     \|__|\|__|\|__|\|__/__/ /\ __\/__/ /\ __\'
      PRINT *, '                       |__|/ \|__||__|/ \|__|'
      PRINT *, '        01001000 01100001 01111000 01111000'
      PRINT *, '   _______  ________'
      PRINT *, '  /  ___  \|\_____  \'
      PRINT *, ' /__/|_/  /\|____|\ /_'
      PRINT *, ' |__|//  / /     \|\  \'
      PRINT *, '     /  /_/__   __\_\  \'
      PRINT *, '    |\________\|\_______\'
      PRINT *, '     \|_______|\|_______|'
      PRINT *, '      00110010 00110011'      
      PRINT *, ' '
      PRINT *, ' **************************************************'
      PRINT *, ' ABAQUS Subroutine for diffusion-reaction transport'
      PRINT *, ' model coupled with a mechanical IVD simulation'
      PRINT *, ' auth: Estefano Muñoz-Moya'
      PRINT *, ' LinkTree: https://linktr.ee/estefano23'
      PRINT *, ' webPage: https://estefano23.github.io/'
      PRINT *, ' github: estefano23'
      PRINT *, ' email: estefano.munoz.moya@gmail.com'
      PRINT *, ' **************************************************'
      PRINT *, ' '
      PRINT *, '--------------'
      PRINT *, 'DIRECTORY INFO'
      PRINT *, '--------------'
      PRINT *, ' '
      PRINT *, 'Current job name: ', JOBNAME
      PRINT *, 'Current job directory: '
      PRINT *, outdir
      PRINT *, 'Temporary directory: '
      PRINT *, cwd
      PRINT *, ' '
      PRINT *, '---------------------------------------------'
      PRINT *, ' '
      PRINT *, 'TYPE OF ELEMENT: C3D20'
      PRINT *, '----------------------'
      PRINT *, ' '
      PRINT *, ' Normalized Nodal Coordinates'
      PRINT *, ' for the shape functions (N)'
      PRINT *, '       x   y    z'
      PRINT *, 'N(1)  -1  -1   -1'
      PRINT *, 'N(2)   1  -1   -1                          \y'
      PRINT *, 'N(3)   1   1   -1                \z       /'
      PRINT *, 'N(4)  -1   1   -1                |       /'
      PRINT *, 'N(5)  -1  -1    1          8-----|15--------7'
      PRINT *, 'N(6)   1  -1    1         /|     |     /   /|'
      PRINT *, 'N(7)   1   1    1        / |     |    /   / |'
      PRINT *, 'N(8)  -1   1    1      16  |     |   /  14  |'
      PRINT *, 'N(9)   0  -1   -1      /  20     |  /   /   19'
      PRINT *, 'N(10)  1   0   -1     /    |     | /   /    |'
      PRINT *, 'N(11)  0   1   -1    5-------13-------6     |'
      PRINT *, 'N(12) -1   0   -1    |     |     +----|--------\x'
      PRINT *, 'N(13)  0  -1    1    |     4-------11-|-----3'
      PRINT *, 'N(14)  1   0    1    |    /           |    /'
      PRINT *, 'N(15)  0   1    1   17   /           18   /'
      PRINT *, 'N(16) -1   0    1    |  12            |  10'
      PRINT *, 'N(17) -1  -1    0    | /              | /'
      PRINT *, 'N(18)  1  -1    0    |/               |/'
      PRINT *, 'N(19)  1   1    0    1--------9-------2'
      PRINT *, 'N(20) -1   1    0'
      PRINT *, ' '
      PRINT *, ' Normalized Integration Point coordinates (Cip)'
      PRINT *, '         ξ   η    ζ'
      PRINT *, 'Cip(1)  -1  -1   -1'
      PRINT *, 'Cip(2)   0  -1   -1'
      PRINT *, 'Cip(3)   1  -1   -1'
      PRINT *, 'Cip(4)  -1   0   -1                          \η'
      PRINT *, 'Cip(5)   0   0   -1                \ζ       /'
      PRINT *, 'Cip(6)   1   0   -1                |       /'
      PRINT *, 'Cip(7)  -1   1   -1         25-----|26-------27'
      PRINT *, 'Cip(8)   0   1   -1         /|     |     /   /|'
      PRINT *, 'Cip(9)   1   1   -1        / |     |    /   / |'
      PRINT *, 'Cip(10) -1  -1    0      22--|----23------24  |'
      PRINT *, 'Cip(11)  0  -1    0      /  16-----|17/---/---18'
      PRINT *, 'Cip(12)  1  -1    0     /   /|     | /   /   /|'
      PRINT *, 'Cip(13) -1   0    0   19-------20------21   / |'
      PRINT *, 'Cip(14)  0   0    0    |  13------14----|-15-----\ξ'
      PRINT *, 'Cip(15)  1   0    0    | /   7-------8--|-/---9'
      PRINT *, 'Cip(16) -1   1    0    |/   /           |/   /'
      PRINT *, 'Cip(17)  0   1    0   10--------11-----12   /'
      PRINT *, 'Cip(18)  1   1    0    |  4 -------5----|--6'
      PRINT *, 'Cip(19) -1  -1    1    | /              | /'
      PRINT *, 'Cip(20)  0  -1    1    |/               |/'
      PRINT *, 'Cip(21)  1  -1    1    1--------2-------3'
      PRINT *, 'Cip(22) -1   0    1   Multiplicative Factor:'
      PRINT *, 'Cip(23)  0   0    1      α = SQR(3/5)'
      PRINT *, 'Cip(24)  1   0    1   ALPHA=0.774596669241483'
      PRINT *, 'Cip(25) -1   1    1'
      PRINT *, 'Cip(26)  0   1    1'
      PRINT *, 'Cip(27)  1   1    1'
      PRINT *, ' '
      PRINT *, '---------------------------------------------'
      PRINT *, ' '
      PRINT *, 'PROBLEM INFO'
      PRINT *, '------------'
      PRINT *, ' '
      PRINT *, 'Number of elements: ', numElem
      PRINT *, 'ID Offset original elements vs UEL: ', ElemOffset
      PRINT *, 'Number of integration points per element: ', numInt
      PRINT *, 'Total number of integration points: ', numElemInt
      PRINT *, 'Larget id number for the UEL elements: ', numIdElem
      PRINT *, ' '

      ELSEIF (LOP .EQ. 5) THEN  !start of the step
      PRINT *, '---------------------------------------------'
      PRINT *, ' '
      PRINT *, 'Start of the step: ', KSTEP
      PRINT *, ' '
      PRINT *, 'Current increment number: ', KINC
      PRINT *, 'Value of current increment time: ', TIME(1)
      PRINT *, 'Value of total time.: ', TIME(2)
      PRINT *, ' '
      PRINT *, '---------------------------------------------'
      PRINT *, ' '

      ELSEIF (LOP .EQ. 1) THEN  !start of the increment
      PRINT *, '---------------------------------------------'
      PRINT *, ' '
      PRINT *, 'Start of the increment: ', KINC
      PRINT *, ' '      
      PRINT *, 'Current step number: ', KSTEP
      PRINT *, 'Value of current increment time: ', TIME(1)
      PRINT *, 'Value of total time.: ', TIME(2)
      PRINT *, ' '
      PRINT *, '---------------------------------------------'
      PRINT *, ' '

      ELSEIF (LOP .EQ. 3) THEN  !end of the analisys
      PRINT *, ' '
      PRINT *, '*********************************************'
      PRINT *, ' '
      PRINT *, 'End of the analisys'
      PRINT *, ' '
      PRINT *, '01001000 01100001 01111000'
      PRINT *, '01001000 01100001 01111000 01111000'
      PRINT *, '00110010 00110011'
      PRINT *, ' '
      PRINT *, ' auth: Estefano Muñoz-Moya'
      PRINT *, ' LinkTree: https://linktr.ee/estefano23'
      PRINT *, ' webPage: https://estefano23.github.io/'
      PRINT *, ' github: estefano23'
      PRINT *, ' email: estefano.munoz.moya@gmail.com'
      PRINT *, ' '
      PRINT *, '*********************************************'
      PRINT *, ' '
      CALL XIT
      END IF
