# Generated by Django 5.1.4 on 2025-01-04 02:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hpk", "0011_alter_splitviewpage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="splitviewpage",
            name="content",
            field=wagtail.fields.StreamField(
                [("rich_text", 0), ("code", 3), ("image", 4), ("icon_link_lists", 14)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.RichTextBlock", (), {}),
                    1: ("wagtail.blocks.TextBlock", (), {"help_text": None, "required": True}),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("python", "Python"),
                                ("javascript", "JavaScript"),
                                ("html", "HTML"),
                                ("css", "CSS"),
                                ("bash", "Bash"),
                                ("plaintext", "Plain Text"),
                            ],
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.StructBlock", [[("code", 1), ("language", 2)]], {}),
                    4: ("hpk.blocks.WrappedImageChooserBlock", (), {}),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional heading for this list (e.g., Social Links).",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 2,
                            "help_text": "Heading level for the list (1-6).",
                            "max_value": 6,
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    7: (
                        "hpk.blocks.HREFBlock",
                        (),
                        {
                            "help_text": "An optional link field",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "The title for the list item.",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Id of the icon in the static/icons.svg file.",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("href", 7), ("label", 8), ("icon", 9)]],
                        {},
                    ),
                    11: ("wagtail.blocks.ListBlock", (10,), {"help_text": "The list of items."}),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 5), ("heading_level", 6), ("items", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [[("link_list", 12)]],
                        {
                            "help_text": "Add one or more heading-and-link-list blocks.",
                            "required": False,
                        },
                    ),
                    14: ("wagtail.blocks.StructBlock", [[("lists", 13)]], {}),
                },
                help_text="Main content for the split-view page.",
            ),
        ),
    ]
