# Generated by Django 5.1.4 on 2025-01-08 23:52

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpk', '0014_alter_article_content_alter_article_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='tagline',
            field=models.CharField(blank=True, help_text='A short tagline for the article.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=wagtail.fields.RichTextField(blank=True, help_text='A summary to be displayed in previews.'),
        ),
    ]
