# Generated by Django 5.1.5 on 2025-01-18 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hpk', '0018_rename_articletag_pagetag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletype',
            old_name='name_plural',
            new_name='_name_plural',
        ),
    ]
