
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-24T14:06:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a2208af7ba51046a0e674061492250deda86a76d",
 "version": "1.2.1-rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
