# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.models.dbv0037_wckey_info import Dbv0037WckeyInfo

class TestDbv0037WckeyInfo(unittest.TestCase):
    """Dbv0037WckeyInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0037WckeyInfo:
        """Test Dbv0037WckeyInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0037WckeyInfo`
        """
        model = Dbv0037WckeyInfo()
        if include_optional:
            return Dbv0037WckeyInfo(
                errors = [
                    aind_slurm_rest.models.dbv0/0/37_error.dbv0.0.37_error(
                        errno = 56, 
                        error = '', )
                    ],
                wckeys = [
                    aind_slurm_rest.models.dbv0/0/37_wckey.dbv0.0.37_wckey(
                        accounts = [
                            ''
                            ], 
                        cluster = '', 
                        id = 56, 
                        name = '', 
                        user = '', 
                        flags = [
                            ''
                            ], )
                    ]
            )
        else:
            return Dbv0037WckeyInfo(
        )
        """

    def testDbv0037WckeyInfo(self):
        """Test Dbv0037WckeyInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
