# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.models.dbv0037_job_wckey import Dbv0037JobWckey

class TestDbv0037JobWckey(unittest.TestCase):
    """Dbv0037JobWckey unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0037JobWckey:
        """Test Dbv0037JobWckey
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0037JobWckey`
        """
        model = Dbv0037JobWckey()
        if include_optional:
            return Dbv0037JobWckey(
                wckey = '',
                flags = [
                    ''
                    ]
            )
        else:
            return Dbv0037JobWckey(
        )
        """

    def testDbv0037JobWckey(self):
        """Test Dbv0037JobWckey"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
