# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.models.dbv0036_config_response import Dbv0036ConfigResponse

class TestDbv0036ConfigResponse(unittest.TestCase):
    """Dbv0036ConfigResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0036ConfigResponse:
        """Test Dbv0036ConfigResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0036ConfigResponse`
        """
        model = Dbv0036ConfigResponse()
        if include_optional:
            return Dbv0036ConfigResponse(
                errors = [
                    aind_slurm_rest.models.dbv0/0/36_error.dbv0.0.36_error(
                        errno = 56, 
                        error = '', )
                    ]
            )
        else:
            return Dbv0036ConfigResponse(
        )
        """

    def testDbv0036ConfigResponse(self):
        """Test Dbv0036ConfigResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
