# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_openapi_get(self) -> None:
        """Test case for openapi_get

        Retrieve OpenAPI Specification
        """
        pass

    def test_openapi_json_get(self) -> None:
        """Test case for openapi_json_get

        Retrieve OpenAPI Specification
        """
        pass

    def test_openapi_v3_get(self) -> None:
        """Test case for openapi_v3_get

        Retrieve OpenAPI Specification
        """
        pass

    def test_openapi_yaml_get(self) -> None:
        """Test case for openapi_yaml_get

        Retrieve OpenAPI Specification
        """
        pass

    def test_slurm_v0035_diag_get(self) -> None:
        """Test case for slurm_v0035_diag_get

        get diagnostics
        """
        pass

    def test_slurm_v0035_job_job_id_delete(self) -> None:
        """Test case for slurm_v0035_job_job_id_delete

        cancel or signal job
        """
        pass

    def test_slurm_v0035_job_job_id_get(self) -> None:
        """Test case for slurm_v0035_job_job_id_get

        get job info
        """
        pass

    def test_slurm_v0035_job_job_id_post(self) -> None:
        """Test case for slurm_v0035_job_job_id_post

        update job
        """
        pass

    def test_slurm_v0035_job_submit_post(self) -> None:
        """Test case for slurm_v0035_job_submit_post

        submit new job
        """
        pass

    def test_slurm_v0035_jobs_get(self) -> None:
        """Test case for slurm_v0035_jobs_get

        get list of jobs
        """
        pass

    def test_slurm_v0035_node_node_name_get(self) -> None:
        """Test case for slurm_v0035_node_node_name_get

        get node info
        """
        pass

    def test_slurm_v0035_nodes_get(self) -> None:
        """Test case for slurm_v0035_nodes_get

        get all node info
        """
        pass

    def test_slurm_v0035_partition_partition_name_get(self) -> None:
        """Test case for slurm_v0035_partition_partition_name_get

        get partition info
        """
        pass

    def test_slurm_v0035_partitions_get(self) -> None:
        """Test case for slurm_v0035_partitions_get

        get all partition info
        """
        pass

    def test_slurm_v0035_ping_get(self) -> None:
        """Test case for slurm_v0035_ping_get

        ping test
        """
        pass


if __name__ == '__main__':
    unittest.main()
