# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.models.dbv0037_qos_limits_max_wall_clock import Dbv0037QosLimitsMaxWallClock

class TestDbv0037QosLimitsMaxWallClock(unittest.TestCase):
    """Dbv0037QosLimitsMaxWallClock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0037QosLimitsMaxWallClock:
        """Test Dbv0037QosLimitsMaxWallClock
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0037QosLimitsMaxWallClock`
        """
        model = Dbv0037QosLimitsMaxWallClock()
        if include_optional:
            return Dbv0037QosLimitsMaxWallClock(
                per = aind_slurm_rest.models.dbv0_0_37_qos_limits_max_wall_clock_per.dbv0_0_37_qos_limits_max_wall_clock_per(
                    qos = 56, 
                    job = 56, )
            )
        else:
            return Dbv0037QosLimitsMaxWallClock(
        )
        """

    def testDbv0037QosLimitsMaxWallClock(self):
        """Test Dbv0037QosLimitsMaxWallClock"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
