# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.models.dbv0036_job_het import Dbv0036JobHet

class TestDbv0036JobHet(unittest.TestCase):
    """Dbv0036JobHet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0036JobHet:
        """Test Dbv0036JobHet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0036JobHet`
        """
        model = Dbv0036JobHet()
        if include_optional:
            return Dbv0036JobHet(
                job_id = 56,
                job_offset = aind_slurm_rest.models.job_offset.job_offset()
            )
        else:
            return Dbv0036JobHet(
        )
        """

    def testDbv0036JobHet(self):
        """Test Dbv0036JobHet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
