# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.models.dbv0037_job import Dbv0037Job

class TestDbv0037Job(unittest.TestCase):
    """Dbv0037Job unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0037Job:
        """Test Dbv0037Job
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0037Job`
        """
        model = Dbv0037Job()
        if include_optional:
            return Dbv0037Job(
                account = '',
                comment = aind_slurm_rest.models.dbv0_0_37_job_comment.dbv0_0_37_job_comment(
                    administrator = '', 
                    job = '', 
                    system = '', ),
                allocation_nodes = '',
                array = aind_slurm_rest.models.dbv0_0_37_job_array.dbv0_0_37_job_array(
                    job_id = 56, 
                    limits = aind_slurm_rest.models.dbv0_0_37_job_array_limits.dbv0_0_37_job_array_limits(
                        max = aind_slurm_rest.models.dbv0_0_37_job_array_limits_max.dbv0_0_37_job_array_limits_max(
                            running = aind_slurm_rest.models.dbv0_0_37_job_array_limits_max_running.dbv0_0_37_job_array_limits_max_running(
                                tasks = 56, ), ), ), 
                    task = '', 
                    task_id = 56, ),
                time = aind_slurm_rest.models.dbv0_0_37_job_time.dbv0_0_37_job_time(
                    elapsed = 56, 
                    eligible = 56, 
                    end = 56, 
                    start = 56, 
                    submission = 56, 
                    suspended = 56, 
                    system = aind_slurm_rest.models.dbv0_0_37_job_time_system.dbv0_0_37_job_time_system(
                        seconds = 56, 
                        microseconds = 56, ), 
                    total = aind_slurm_rest.models.dbv0_0_37_job_time_total.dbv0_0_37_job_time_total(
                        seconds = 56, 
                        microseconds = 56, ), 
                    user = aind_slurm_rest.models.dbv0_0_37_job_time_user.dbv0_0_37_job_time_user(
                        seconds = 56, 
                        microseconds = 56, ), 
                    limit = 56, ),
                association = aind_slurm_rest.models.dbv0/0/37_association_short_info.dbv0.0.37_association_short_info(
                    account = '', 
                    cluster = '', 
                    partition = '', 
                    user = '', ),
                cluster = '',
                constraints = '',
                derived_exit_code = aind_slurm_rest.models.dbv0/0/37_job_exit_code.dbv0.0.37_job_exit_code(
                    status = '', 
                    return_code = 56, 
                    signal = aind_slurm_rest.models.dbv0_0_37_job_exit_code_signal.dbv0_0_37_job_exit_code_signal(
                        signal_id = 56, 
                        name = '', ), ),
                exit_code = aind_slurm_rest.models.dbv0/0/37_job_exit_code.dbv0.0.37_job_exit_code(
                    status = '', 
                    return_code = 56, 
                    signal = aind_slurm_rest.models.dbv0_0_37_job_exit_code_signal.dbv0_0_37_job_exit_code_signal(
                        signal_id = 56, 
                        name = '', ), ),
                flags = [
                    ''
                    ],
                group = '',
                het = aind_slurm_rest.models.dbv0_0_37_job_het.dbv0_0_37_job_het(
                    job_id = aind_slurm_rest.models.job_id.job_id(), 
                    job_offset = aind_slurm_rest.models.job_offset.job_offset(), ),
                job_id = 56,
                name = '',
                mcs = aind_slurm_rest.models.dbv0_0_37_job_mcs.dbv0_0_37_job_mcs(
                    label = '', ),
                nodes = '',
                partition = '',
                priority = 56,
                qos = '',
                required = aind_slurm_rest.models.dbv0_0_37_job_required.dbv0_0_37_job_required(
                    cpus = 56, 
                    memory = 56, ),
                kill_request_user = '',
                reservation = aind_slurm_rest.models.dbv0_0_37_job_reservation.dbv0_0_37_job_reservation(
                    id = 56, 
                    name = 56, ),
                state = aind_slurm_rest.models.dbv0_0_37_job_state.dbv0_0_37_job_state(
                    current = '', 
                    reason = '', ),
                steps = [
                    aind_slurm_rest.models.dbv0/0/37_job_step.dbv0.0.37_job_step(
                        time = aind_slurm_rest.models.dbv0_0_37_job_step_time.dbv0_0_37_job_step_time(
                            elapsed = 56, 
                            end = 56, 
                            start = 56, 
                            suspended = 56, 
                            system = aind_slurm_rest.models.dbv0_0_37_job_time_system.dbv0_0_37_job_time_system(
                                seconds = 56, 
                                microseconds = 56, ), 
                            total = aind_slurm_rest.models.dbv0_0_37_job_time_total.dbv0_0_37_job_time_total(
                                seconds = 56, 
                                microseconds = 56, ), 
                            user = aind_slurm_rest.models.dbv0_0_37_job_time_user.dbv0_0_37_job_time_user(
                                seconds = 56, 
                                microseconds = 56, ), ), 
                        exit_code = aind_slurm_rest.models.dbv0/0/37_job_exit_code.dbv0.0.37_job_exit_code(
                            status = '', 
                            return_code = 56, 
                            signal = aind_slurm_rest.models.dbv0_0_37_job_exit_code_signal.dbv0_0_37_job_exit_code_signal(
                                signal_id = 56, 
                                name = '', ), ), 
                        nodes = aind_slurm_rest.models.dbv0_0_37_job_step_nodes.dbv0_0_37_job_step_nodes(
                            count = 56, 
                            range = '', ), 
                        tasks = aind_slurm_rest.models.dbv0_0_37_job_step_tasks.dbv0_0_37_job_step_tasks(
                            count = 56, ), 
                        pid = '', 
                        cpu = aind_slurm_rest.models.dbv0_0_37_job_step_cpu.dbv0_0_37_job_step_CPU(
                            requested_frequency = aind_slurm_rest.models.dbv0_0_37_job_step_cpu_requested_frequency.dbv0_0_37_job_step_CPU_requested_frequency(
                                min = 56, 
                                max = 56, ), 
                            governor = [
                                ''
                                ], ), 
                        kill_request_user = '', 
                        state = '', 
                        statistics = aind_slurm_rest.models.dbv0_0_37_job_step_statistics.dbv0_0_37_job_step_statistics(
                            energy = aind_slurm_rest.models.dbv0_0_37_job_step_statistics_energy.dbv0_0_37_job_step_statistics_energy(
                                consumed = 56, ), ), 
                        step = aind_slurm_rest.models.dbv0_0_37_job_step_step.dbv0_0_37_job_step_step(
                            job_id = 56, 
                            het = aind_slurm_rest.models.dbv0_0_37_job_step_step_het.dbv0_0_37_job_step_step_het(
                                component = 56, ), 
                            id = '', 
                            name = '', ), 
                        task = aind_slurm_rest.models.dbv0_0_37_job_step_task.dbv0_0_37_job_step_task(
                            distribution = '', ), 
                        tres = aind_slurm_rest.models.dbv0_0_37_job_step_tres.dbv0_0_37_job_step_tres(
                            requested = aind_slurm_rest.models.dbv0_0_37_job_step_tres_requested.dbv0_0_37_job_step_tres_requested(
                                average = [
                                    aind_slurm_rest.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                                        type = '', 
                                        name = '', 
                                        id = 56, 
                                        count = 56, )
                                    ], 
                                max = [
                                    aind_slurm_rest.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                                        type = '', 
                                        name = '', 
                                        id = 56, 
                                        count = 56, )
                                    ], 
                                min = , ), 
                            consumed = aind_slurm_rest.models.dbv0_0_37_job_step_tres_requested.dbv0_0_37_job_step_tres_requested(), 
                            allocated = , ), )
                    ],
                tres = aind_slurm_rest.models.dbv0_0_37_job_tres.dbv0_0_37_job_tres(
                    allocated = [
                        aind_slurm_rest.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], 
                    requested = [
                        aind_slurm_rest.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ], ),
                user = '',
                wckey = aind_slurm_rest.models.dbv0_0_37_job_wckey.dbv0_0_37_job_wckey(
                    flags = [
                        ''
                        ], ),
                working_directory = ''
            )
        else:
            return Dbv0037Job(
        )
        """

    def testDbv0037Job(self):
        """Test Dbv0037Job"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
