# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.models.dbv0037_job_exit_code_signal import Dbv0037JobExitCodeSignal

class TestDbv0037JobExitCodeSignal(unittest.TestCase):
    """Dbv0037JobExitCodeSignal unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0037JobExitCodeSignal:
        """Test Dbv0037JobExitCodeSignal
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0037JobExitCodeSignal`
        """
        model = Dbv0037JobExitCodeSignal()
        if include_optional:
            return Dbv0037JobExitCodeSignal(
                signal_id = 56,
                name = ''
            )
        else:
            return Dbv0037JobExitCodeSignal(
        )
        """

    def testDbv0037JobExitCodeSignal(self):
        """Test Dbv0037JobExitCodeSignal"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
