# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_slurm_rest.models.dbv0036_qos_limits_max_jobs_per import Dbv0036QosLimitsMaxJobsPer

class TestDbv0036QosLimitsMaxJobsPer(unittest.TestCase):
    """Dbv0036QosLimitsMaxJobsPer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0036QosLimitsMaxJobsPer:
        """Test Dbv0036QosLimitsMaxJobsPer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0036QosLimitsMaxJobsPer`
        """
        model = Dbv0036QosLimitsMaxJobsPer()
        if include_optional:
            return Dbv0036QosLimitsMaxJobsPer(
                account = 56,
                user = 56
            )
        else:
            return Dbv0036QosLimitsMaxJobsPer(
        )
        """

    def testDbv0036QosLimitsMaxJobsPer(self):
        """Test Dbv0036QosLimitsMaxJobsPer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
