# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CreateFeedbackRequest(BaseModel):
    """
    CreateFeedbackRequest
    """ # noqa: E501
    message_id: StrictStr
    channel_id: StrictStr
    account_id: StrictStr
    parent_id: StrictStr
    user_query: StrictStr
    slm_leaderboard: Dict[str, Any]
    sources: List[Dict[str, Any]]
    artifacts: List[Dict[str, Any]]
    feedback_id: StrictStr
    feedback_type: StrictStr
    feedback_category: Optional[StrictStr]
    feedback_details: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["message_id", "channel_id", "account_id", "parent_id", "user_query", "slm_leaderboard", "sources", "artifacts", "feedback_id", "feedback_type", "feedback_category", "feedback_details"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateFeedbackRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if feedback_category (nullable) is None
        # and model_fields_set contains the field
        if self.feedback_category is None and "feedback_category" in self.model_fields_set:
            _dict['feedback_category'] = None

        # set to None if feedback_details (nullable) is None
        # and model_fields_set contains the field
        if self.feedback_details is None and "feedback_details" in self.model_fields_set:
            _dict['feedback_details'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateFeedbackRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message_id": obj.get("message_id"),
            "channel_id": obj.get("channel_id"),
            "account_id": obj.get("account_id"),
            "parent_id": obj.get("parent_id"),
            "user_query": obj.get("user_query"),
            "slm_leaderboard": obj.get("slm_leaderboard"),
            "sources": obj.get("sources"),
            "artifacts": obj.get("artifacts"),
            "feedback_id": obj.get("feedback_id"),
            "feedback_type": obj.get("feedback_type"),
            "feedback_category": obj.get("feedback_category"),
            "feedback_details": obj.get("feedback_details")
        })
        return _obj


