# Copyright 2022 OpenSynergy Indonesia
# Copyright 2022 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).
{
    "name": "School",
    "version": "14.0.1.0.0",
    "website": "https://simetri-sinergi.id",
    "author": "PT. Simetri Sinergi Indonesia, OpenSynergy Indonesia",
    "license": "AGPL-3",
    "installable": True,
    "application": True,
    "depends": [
        "ssi_master_data_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
    ],
    "data": [
        "security/ir_module_category_data.xml",
        "security/ir_module_category/school_curiculum.xml",
        "security/ir_module_category/school_enrollment.xml",
        "security/ir_module_category/school_class.xml",
        "security/ir_module_category/school_report_card.xml",
        "security/res_group_data.xml",
        "security/res_group/school_ccuriculum.xml",
        "security/res_group/school_enrollment.xml",
        "security/res_group/school_class.xml",
        "security/res_group/school_report_card.xml",
        "security/ir_model_access/school_subject.xml",
        "security/ir_model_access/school_grade_type.xml",
        "security/ir_model_access/school_grade.xml",
        "security/ir_model_access/school_student.xml",
        "security/ir_model_access/school_teacher.xml",
        "security/ir_model_access/school_academic_year.xml",
        "security/ir_model_access/school_academic_term.xml",
        "security/ir_model_access/school_subject_grade.xml",
        "security/ir_model_access/school_curiculum.xml",
        "security/ir_model_access/school_enrollment.xml",
        "security/ir_model_access/school_class.xml",
        "security/ir_model_access/school_report_card.xml",
        "security/ir_model_access/school_student_class_assignment.xml",
        "security/ir_rule/school_curiculum.xml",
        "security/ir_rule/school_enrollment.xml",
        "security/ir_rule/school_class.xml",
        "security/ir_rule/school_report_card.xml",
        "ir_sequence/school_curiculum.xml",
        "ir_sequence/school_enrollment.xml",
        "ir_sequence/school_class.xml",
        "ir_sequence/school_report_card.xml",
        "sequence_template/school_curiculum.xml",
        "sequence_template/school_enrollment.xml",
        "sequence_template/school_class.xml",
        "sequence_template/school_report_card.xml",
        "policy_template/school_curiculum.xml",
        "policy_template/school_enrollment.xml",
        "policy_template/school_class.xml",
        "policy_template/school_report_card.xml",
        "approval_template/school_curiculum.xml",
        "approval_template/school_enrollment.xml",
        "approval_template/school_class.xml",
        "approval_template/school_report_card.xml",
        "menu.xml",
        "views/school_subject.xml",
        "views/school_grade_type.xml",
        "views/school_grade.xml",
        "views/school_student.xml",
        "views/school_teacher.xml",
        "views/school_academic_year.xml",
        "views/school_academic_term.xml",
        "views/school_subject_grade.xml",
        "views/school_curiculum.xml",
        "views/school_enrollment.xml",
        "views/school_class.xml",
        "views/school_report_card.xml",
    ],
    "demo": [
        "demo/school_grade_type.xml",
        "demo/school_grade.xml",
        "demo/school_subject.xml",
        "demo/school_academic_year.xml",
        "demo/school_academic_term.xml",
    ],
}
