
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-25T09:16:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2df30ddec0ba4ab851618d7cdf0f502545940185",
 "version": "1.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
