# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ephor_server_ti_client.models.transcript import Transcript

class TestTranscript(unittest.TestCase):
    """Transcript unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Transcript:
        """Test Transcript
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Transcript`
        """
        model = Transcript()
        if include_optional:
            return Transcript(
                id = '',
                account_id = '',
                stage = 'active',
                created_at = '',
                messages = [
                    ephor_server_ti_client.models.transcript_message.TranscriptMessage(
                        id = '', 
                        created_at = '', 
                        participant_id = '', 
                        participant_name = '', 
                        content = '', 
                        transcript_id = '', 
                        account_id = '', 
                        mapped_question_id = '', 
                        seconds_elapsed_on_question = 56, )
                    ],
                updated_at = '',
                question = '',
                seconds_elapsed_on_question = 56,
                reflections = ''
            )
        else:
            return Transcript(
                id = '',
                account_id = '',
                created_at = '',
                messages = [
                    ephor_server_ti_client.models.transcript_message.TranscriptMessage(
                        id = '', 
                        created_at = '', 
                        participant_id = '', 
                        participant_name = '', 
                        content = '', 
                        transcript_id = '', 
                        account_id = '', 
                        mapped_question_id = '', 
                        seconds_elapsed_on_question = 56, )
                    ],
                updated_at = '',
        )
        """

    def testTranscript(self):
        """Test Transcript"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
