# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ephor_server_ti_client.api.redis_api import RedisApi


class TestRedisApi(unittest.TestCase):
    """RedisApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RedisApi()

    def tearDown(self) -> None:
        pass

    def test_get_bot_dispatch_session_api_v1_redis_botdispatch_session_get(self) -> None:
        """Test case for get_bot_dispatch_session_api_v1_redis_botdispatch_session_get

        Get Bot Dispatch Session
        """
        pass

    def test_get_breadcrumbs_api_v1_redis_breadcrumbs_types_post(self) -> None:
        """Test case for get_breadcrumbs_api_v1_redis_breadcrumbs_types_post

        Get Breadcrumbs
        """
        pass

    def test_set_bot_dispatch_session_api_v1_redis_botdispatch_session_post(self) -> None:
        """Test case for set_bot_dispatch_session_api_v1_redis_botdispatch_session_post

        Set Bot Dispatch Session
        """
        pass

    def test_store_api_v1_redis_store_post(self) -> None:
        """Test case for store_api_v1_redis_store_post

        Store
        """
        pass


if __name__ == '__main__':
    unittest.main()
