# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ephor_server_ti_client.models.project_update import ProjectUpdate

class TestProjectUpdate(unittest.TestCase):
    """ProjectUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectUpdate:
        """Test ProjectUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectUpdate`
        """
        model = ProjectUpdate()
        if include_optional:
            return ProjectUpdate(
                name = '',
                description = '',
                collection = [
                    ephor_server_ti_client.models.collection_item.CollectionItem(
                        namespace = '', 
                        document_id = '', )
                    ],
                library = ephor_server_ti_client.models.library.Library(
                    library_id = '', 
                    items = [
                        ephor_server_ti_client.models.library_item.LibraryItem(
                            index_reference = '', 
                            name = '', 
                            manifest = [
                                ephor_server_ti_client.models.manifest_item.ManifestItem(
                                    id = '', 
                                    mime_type = '', 
                                    name = '', 
                                    web_view_link = '', 
                                    starred = True, 
                                    priority = 56, 
                                    ingested = True, 
                                    ingestion_status = '', 
                                    ingestion_error = '', 
                                    updated_at = '', 
                                    content_hash = '', 
                                    type = '', )
                                ], 
                            is_multipart = True, 
                            last_part = 56, )
                        ], ),
                users = {
                    'key' : ''
                    },
                predefined_queries = [
                    ''
                    ],
                custom_instructions = '',
                model = '',
                comments = [
                    ephor_server_ti_client.models.comment.Comment(
                        comment_id = '', 
                        account_id = '', 
                        content = '', 
                        timestamp = '', )
                    ],
                updated_at = ''
            )
        else:
            return ProjectUpdate(
        )
        """

    def testProjectUpdate(self):
        """Test ProjectUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
