# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ephor_server_ti_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_create_or_connect_sandbox_api_v1_interact_tasks_artifacts_sandbox_post_0(self) -> None:
        """Test case for create_or_connect_sandbox_api_v1_interact_tasks_artifacts_sandbox_post_0

        Create Or Connect Sandbox
        """
        pass

    def test_execute_code_api_v1_interact_tasks_artifacts_execute_post_0(self) -> None:
        """Test case for execute_code_api_v1_interact_tasks_artifacts_execute_post_0

        Execute Code
        """
        pass

    def test_generate_react_api_v1_interact_tasks_artifacts_generate_react_post_0(self) -> None:
        """Test case for generate_react_api_v1_interact_tasks_artifacts_generate_react_post_0

        Generate React
        """
        pass

    def test_generate_streamlit_api_v1_interact_tasks_artifacts_generate_streamlit_post_0(self) -> None:
        """Test case for generate_streamlit_api_v1_interact_tasks_artifacts_generate_streamlit_post_0

        Generate Streamlit
        """
        pass

    def test_text_qna_api_v1_interact_tasks_text_post_0(self) -> None:
        """Test case for text_qna_api_v1_interact_tasks_text_post_0

        Text Qna
        """
        pass


if __name__ == '__main__':
    unittest.main()
