# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ephor_server_ti_client.models.attachment_upload_request import AttachmentUploadRequest

class TestAttachmentUploadRequest(unittest.TestCase):
    """AttachmentUploadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttachmentUploadRequest:
        """Test AttachmentUploadRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttachmentUploadRequest`
        """
        model = AttachmentUploadRequest()
        if include_optional:
            return AttachmentUploadRequest(
                attachment_id = '',
                file_content = '',
                used_tokens = 56
            )
        else:
            return AttachmentUploadRequest(
                attachment_id = '',
                file_content = '',
        )
        """

    def testAttachmentUploadRequest(self):
        """Test AttachmentUploadRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
