# coding: utf-8

"""
    Ephor.ai

    Collaborative AI

    The version of the OpenAPI document: 1.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ephor_server_ti_client.api.account_api import AccountApi


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountApi()

    def tearDown(self) -> None:
        pass

    def test_delete_command_api_v1_account_commands_command_id_delete(self) -> None:
        """Test case for delete_command_api_v1_account_commands_command_id_delete

        Delete Command
        """
        pass

    def test_delete_google_integration_api_v1_account_oauth_google_delete(self) -> None:
        """Test case for delete_google_integration_api_v1_account_oauth_google_delete

        Delete Google Integration
        """
        pass

    def test_generate_api_key_api_v1_account_api_key_post(self) -> None:
        """Test case for generate_api_key_api_v1_account_api_key_post

        Generate Api Key
        """
        pass

    def test_get_account_id_api_v1_account_id_get(self) -> None:
        """Test case for get_account_id_api_v1_account_id_get

        Get Account Id
        """
        pass

    def test_get_active_api_keys_route_api_v1_account_api_key_get(self) -> None:
        """Test case for get_active_api_keys_route_api_v1_account_api_key_get

        Get Active Api Keys Route
        """
        pass

    def test_get_available_commands_api_v1_account_commands_get(self) -> None:
        """Test case for get_available_commands_api_v1_account_commands_get

        Get Available Commands
        """
        pass

    def test_get_clerk_google_token_api_v1_account_clerk_google_get(self) -> None:
        """Test case for get_clerk_google_token_api_v1_account_clerk_google_get

        Get Clerk Google Token
        """
        pass

    def test_get_command_api_v1_account_commands_command_id_get(self) -> None:
        """Test case for get_command_api_v1_account_commands_command_id_get

        Get Command
        """
        pass

    def test_get_current_profile_api_v1_account_profile_get(self) -> None:
        """Test case for get_current_profile_api_v1_account_profile_get

        Get Current Profile
        """
        pass

    def test_get_google_integration_api_v1_account_oauth_google_get(self) -> None:
        """Test case for get_google_integration_api_v1_account_oauth_google_get

        Get Google Integration
        """
        pass

    def test_get_google_integration_status_api_v1_account_oauth_google_status_get(self) -> None:
        """Test case for get_google_integration_status_api_v1_account_oauth_google_status_get

        Get Google Integration Status
        """
        pass

    def test_get_profile_api_v1_account_profile_account_id_get(self) -> None:
        """Test case for get_profile_api_v1_account_profile_account_id_get

        Get Profile
        """
        pass

    def test_get_profile_summary_api_v1_account_profile_summary_get(self) -> None:
        """Test case for get_profile_summary_api_v1_account_profile_summary_get

        Get Profile Summary
        """
        pass

    def test_get_public_profile_api_v1_account_public_profile_account_id_get(self) -> None:
        """Test case for get_public_profile_api_v1_account_public_profile_account_id_get

        Get Public Profile
        """
        pass

    def test_get_user_activities_api_v1_account_profile_activities_get(self) -> None:
        """Test case for get_user_activities_api_v1_account_profile_activities_get

        Get User Activities
        """
        pass

    def test_oauth_google_authorize_api_v1_account_oauth_google_authorize_get(self) -> None:
        """Test case for oauth_google_authorize_api_v1_account_oauth_google_authorize_get

        Oauth Google Authorize
        """
        pass

    def test_oauth_google_callback_api_v1_account_oauth_google_callback_get(self) -> None:
        """Test case for oauth_google_callback_api_v1_account_oauth_google_callback_get

        Oauth Google Callback
        """
        pass

    def test_revoke_api_key_api_v1_account_api_key_delete(self) -> None:
        """Test case for revoke_api_key_api_v1_account_api_key_delete

        Revoke Api Key
        """
        pass

    def test_search_users_endpoint_api_v1_account_search_get(self) -> None:
        """Test case for search_users_endpoint_api_v1_account_search_get

        Search Users Endpoint
        """
        pass

    def test_update_integrations_api_v1_account_integrations_put(self) -> None:
        """Test case for update_integrations_api_v1_account_integrations_put

        Update Integrations
        """
        pass

    def test_upsert_command_api_v1_account_commands_put(self) -> None:
        """Test case for upsert_command_api_v1_account_commands_put

        Upsert Command
        """
        pass


if __name__ == '__main__':
    unittest.main()
