#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2406-118-g5292a09c"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2406
#define NETGEN_VERSION_TWEAK 118
#define NETGEN_VERSION_HASH "g5292a09c"
#endif // NETGEN_VERSION_HPP_INCLUDED
