
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-01-25T14:13:18+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "26f69a50e70572123d6199645468ddd73e038765",
 "version": "1.2.1-rc6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
