# coding: utf-8

"""
    Screening AI API Docs

    API Documentation for Screening AI

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from screening_ai.models.screening_form_submission_question_dto import ScreeningFormSubmissionQuestionDto

class TestScreeningFormSubmissionQuestionDto(unittest.TestCase):
    """ScreeningFormSubmissionQuestionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScreeningFormSubmissionQuestionDto:
        """Test ScreeningFormSubmissionQuestionDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScreeningFormSubmissionQuestionDto`
        """
        model = ScreeningFormSubmissionQuestionDto()
        if include_optional:
            return ScreeningFormSubmissionQuestionDto(
                index = 1.337,
                agent = '',
                human = '',
                human_audio_url = '',
                answer_type = '',
                answers_given = [
                    ''
                    ]
            )
        else:
            return ScreeningFormSubmissionQuestionDto(
                index = 1.337,
                agent = '',
                human = '',
                human_audio_url = '',
                answer_type = '',
                answers_given = [
                    ''
                    ],
        )
        """

    def testScreeningFormSubmissionQuestionDto(self):
        """Test ScreeningFormSubmissionQuestionDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
