# coding: utf-8

"""
    Screening AI API Docs

    API Documentation for Screening AI

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from screening_ai.models.platform_organisation_response_dto import PlatformOrganisationResponseDto

class TestPlatformOrganisationResponseDto(unittest.TestCase):
    """PlatformOrganisationResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlatformOrganisationResponseDto:
        """Test PlatformOrganisationResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlatformOrganisationResponseDto`
        """
        model = PlatformOrganisationResponseDto()
        if include_optional:
            return PlatformOrganisationResponseDto(
                org_id = '',
                org_name = '',
                org_alias = '',
                org_dp_url = '',
                org_super_admin = '',
                org_admins = [
                    ''
                    ],
                org_joined_at = '',
                org_country = '',
                org_city = '',
                org_state = '',
                org_active = True,
                created_at = '',
                updated_at = ''
            )
        else:
            return PlatformOrganisationResponseDto(
                org_id = '',
                org_name = '',
                org_alias = '',
                org_dp_url = '',
                org_super_admin = '',
                org_admins = [
                    ''
                    ],
                org_joined_at = '',
                org_country = '',
                org_city = '',
                org_state = '',
                org_active = True,
                created_at = '',
                updated_at = '',
        )
        """

    def testPlatformOrganisationResponseDto(self):
        """Test PlatformOrganisationResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
