# coding: utf-8

"""
    Screening AI API Docs

    API Documentation for Screening AI

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from screening_ai.models.platform_user_jwt_response_dto import PlatformUserJwtResponseDto

class TestPlatformUserJwtResponseDto(unittest.TestCase):
    """PlatformUserJwtResponseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlatformUserJwtResponseDto:
        """Test PlatformUserJwtResponseDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlatformUserJwtResponseDto`
        """
        model = PlatformUserJwtResponseDto()
        if include_optional:
            return PlatformUserJwtResponseDto(
                jwt = ''
            )
        else:
            return PlatformUserJwtResponseDto(
                jwt = '',
        )
        """

    def testPlatformUserJwtResponseDto(self):
        """Test PlatformUserJwtResponseDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
